server:
  port: 8097
spring:
  application:
    name: config-server
  cloud:
    inetutils:
      useOnlySiteLocalInterfaces: true
      preferredNetworks:
        - 10.0
    config:
      server:
        git:
          uri: https://github.com/iesorokin/om-configs.git
          searchPaths: '{application}'
        prefix: /config
      fail-fast: true

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
    instanceId: localhost:8097
    preferIpAddress: ${REGISTER_WITH_IP:false}
  client:
    registerWithEureka: true
#    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REPLICASET:http://localhost:8097/eureka/}

logging:
  level:
    ROOT: INFO
    com.netflix.discovery.shared.resolver.aws: WARN
    org.zalando.logbook.Logbook: TRACE
  pattern:
    console: "${spring.application.name} %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%X{transactionId},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}]){blue}[%thread] %clr(%-5level) %clr(%logger{36}){magenta} - %msg%n"
